[package]

name = "libaio"
version = "0.0.1"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
description = "Binding to Linux's async block IO syscalls and libaio"
readme = "README.md"
license = "MIT"

[dependencies]
eventfd= { git = "https://github.com/domsj/eventfd-rust", rev = "5984e220ad9603bb8f2c74080cc24990c05ff279" }
libc="*"
chrono = "*"
aligned_alloc = "*"

[dependencies.nix]
git = "https://github.com/domsj/nix"
rev = "2fb6ef34e6ed5a96a77dd9b7cfee57f2dc129321"
features = [ "eventfd" ]

[dev-dependencies]
tempdir = "*"
